//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for coherentScattering complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coherentScattering">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="scatteringFactor" type="{}coherentScattering_subform"/>
 *           &lt;element name="realAnomalousFactor" type="{}coherentScattering_subform" minOccurs="0"/>
 *           &lt;element name="imaginaryAnomalousFactor" type="{}coherentScattering_subform" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="productFrame" use="required" type="{}frame" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coherentScattering", propOrder = {
    "scatteringFactor",
    "realAnomalousFactor",
    "imaginaryAnomalousFactor"
})
public class CoherentScattering {

    @XmlElement(required = true)
    protected CoherentScatteringSubform scatteringFactor;
    protected CoherentScatteringSubform realAnomalousFactor;
    protected CoherentScatteringSubform imaginaryAnomalousFactor;
    @XmlAttribute(name = "label", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String label;
    @XmlAttribute(name = "productFrame", required = true)
    protected Frame productFrame;

    /**
     * Gets the value of the scatteringFactor property.
     * 
     * @return
     *     possible object is
     *     {@link CoherentScatteringSubform }
     *     
     */
    public CoherentScatteringSubform getScatteringFactor() {
        return scatteringFactor;
    }

    /**
     * Sets the value of the scatteringFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoherentScatteringSubform }
     *     
     */
    public void setScatteringFactor(CoherentScatteringSubform value) {
        this.scatteringFactor = value;
    }

    /**
     * Gets the value of the realAnomalousFactor property.
     * 
     * @return
     *     possible object is
     *     {@link CoherentScatteringSubform }
     *     
     */
    public CoherentScatteringSubform getRealAnomalousFactor() {
        return realAnomalousFactor;
    }

    /**
     * Sets the value of the realAnomalousFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoherentScatteringSubform }
     *     
     */
    public void setRealAnomalousFactor(CoherentScatteringSubform value) {
        this.realAnomalousFactor = value;
    }

    /**
     * Gets the value of the imaginaryAnomalousFactor property.
     * 
     * @return
     *     possible object is
     *     {@link CoherentScatteringSubform }
     *     
     */
    public CoherentScatteringSubform getImaginaryAnomalousFactor() {
        return imaginaryAnomalousFactor;
    }

    /**
     * Sets the value of the imaginaryAnomalousFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoherentScatteringSubform }
     *     
     */
    public void setImaginaryAnomalousFactor(CoherentScatteringSubform value) {
        this.imaginaryAnomalousFactor = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the productFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Frame }
     *     
     */
    public Frame getProductFrame() {
        return productFrame;
    }

    /**
     * Sets the value of the productFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame }
     *     
     */
    public void setProductFrame(Frame value) {
        this.productFrame = value;
    }

}
