//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for coherentScattering_subform complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="coherentScattering_subform">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="XYs1d" type="{}xData_XYs1d_primary"/>
 *         &lt;element name="regions1d" type="{}xData_regions_1d_primary"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "coherentScattering_subform", propOrder = {
    "xYs1D",
    "regions1D"
})
public class CoherentScatteringSubform {

    @XmlElement(name = "XYs1d")
    protected XDataXYs1DPrimary xYs1D;
    @XmlElement(name = "regions1d")
    protected XDataRegions1DPrimary regions1D;

    /**
     * Gets the value of the xYs1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataXYs1DPrimary }
     *     
     */
    public XDataXYs1DPrimary getXYs1D() {
        return xYs1D;
    }

    /**
     * Sets the value of the xYs1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataXYs1DPrimary }
     *     
     */
    public void setXYs1D(XDataXYs1DPrimary value) {
        this.xYs1D = value;
    }

    /**
     * Gets the value of the regions1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataRegions1DPrimary }
     *     
     */
    public XDataRegions1DPrimary getRegions1D() {
        return regions1D;
    }

    /**
     * Sets the value of the regions1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataRegions1DPrimary }
     *     
     */
    public void setRegions1D(XDataRegions1DPrimary value) {
        this.regions1D = value;
    }

}
