//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for constantScatteringRadius complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="constantScatteringRadius">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="domainMin" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domainMax" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domainUnit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "constantScatteringRadius")
public class ConstantScatteringRadius {

    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "value", required = true)
    protected double value;
    @XmlAttribute(name = "unit", required = true)
    protected String unit;
    @XmlAttribute(name = "domainMin")
    protected Double domainMin;
    @XmlAttribute(name = "domainMax")
    protected Double domainMax;
    @XmlAttribute(name = "domainUnit")
    protected String domainUnit;

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the unit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnit() {
        return unit;
    }

    /**
     * Sets the value of the unit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnit(String value) {
        this.unit = value;
    }

    /**
     * Gets the value of the domainMin property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDomainMin() {
        return domainMin;
    }

    /**
     * Sets the value of the domainMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDomainMin(Double value) {
        this.domainMin = value;
    }

    /**
     * Gets the value of the domainMax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDomainMax() {
        return domainMax;
    }

    /**
     * Sets the value of the domainMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDomainMax(Double value) {
        this.domainMax = value;
    }

    /**
     * Gets the value of the domainUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainUnit() {
        return domainUnit;
    }

    /**
     * Sets the value of the domainUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainUnit(String value) {
        this.domainUnit = value;
    }

}
