//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoulombExpansion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoulombExpansion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nuclearTerm" type="{}CoulombExpansionTerm"/>
 *         &lt;element name="realInterferenceTerm" type="{}CoulombExpansionTerm"/>
 *         &lt;element name="imaginaryInterferenceTerm" type="{}CoulombExpansionTerm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoulombExpansion", propOrder = {
    "nuclearTerm",
    "realInterferenceTerm",
    "imaginaryInterferenceTerm"
})
public class CoulombExpansion {

    @XmlElement(required = true)
    protected CoulombExpansionTerm nuclearTerm;
    @XmlElement(required = true)
    protected CoulombExpansionTerm realInterferenceTerm;
    @XmlElement(required = true)
    protected CoulombExpansionTerm imaginaryInterferenceTerm;

    /**
     * Gets the value of the nuclearTerm property.
     * 
     * @return
     *     possible object is
     *     {@link CoulombExpansionTerm }
     *     
     */
    public CoulombExpansionTerm getNuclearTerm() {
        return nuclearTerm;
    }

    /**
     * Sets the value of the nuclearTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoulombExpansionTerm }
     *     
     */
    public void setNuclearTerm(CoulombExpansionTerm value) {
        this.nuclearTerm = value;
    }

    /**
     * Gets the value of the realInterferenceTerm property.
     * 
     * @return
     *     possible object is
     *     {@link CoulombExpansionTerm }
     *     
     */
    public CoulombExpansionTerm getRealInterferenceTerm() {
        return realInterferenceTerm;
    }

    /**
     * Sets the value of the realInterferenceTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoulombExpansionTerm }
     *     
     */
    public void setRealInterferenceTerm(CoulombExpansionTerm value) {
        this.realInterferenceTerm = value;
    }

    /**
     * Gets the value of the imaginaryInterferenceTerm property.
     * 
     * @return
     *     possible object is
     *     {@link CoulombExpansionTerm }
     *     
     */
    public CoulombExpansionTerm getImaginaryInterferenceTerm() {
        return imaginaryInterferenceTerm;
    }

    /**
     * Sets the value of the imaginaryInterferenceTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoulombExpansionTerm }
     *     
     */
    public void setImaginaryInterferenceTerm(CoulombExpansionTerm value) {
        this.imaginaryInterferenceTerm = value;
    }

}
