//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for crossSectionSum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="crossSectionSum">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="documentation" type="{}documentation" minOccurs="0"/>
 *         &lt;element name="summands" type="{}summands"/>
 *         &lt;element name="Q" type="{}Q"/>
 *         &lt;element ref="{}crossSection"/>
 *       &lt;/sequence>
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ENDF_MT" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "crossSectionSum", propOrder = {
    "documentation",
    "summands",
    "q",
    "crossSection"
})
public class CrossSectionSum {

    protected Documentation documentation;
    @XmlElement(required = true)
    protected Summands summands;
    @XmlElement(name = "Q", required = true)
    protected Q q;
    @XmlElement(required = true)
    protected CrossSection crossSection;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "ENDF_MT", required = true)
    protected BigInteger endfmt;

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link Documentation }
     *     
     */
    public Documentation getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documentation }
     *     
     */
    public void setDocumentation(Documentation value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the summands property.
     * 
     * @return
     *     possible object is
     *     {@link Summands }
     *     
     */
    public Summands getSummands() {
        return summands;
    }

    /**
     * Sets the value of the summands property.
     * 
     * @param value
     *     allowed object is
     *     {@link Summands }
     *     
     */
    public void setSummands(Summands value) {
        this.summands = value;
    }

    /**
     * Gets the value of the q property.
     * 
     * @return
     *     possible object is
     *     {@link Q }
     *     
     */
    public Q getQ() {
        return q;
    }

    /**
     * Sets the value of the q property.
     * 
     * @param value
     *     allowed object is
     *     {@link Q }
     *     
     */
    public void setQ(Q value) {
        this.q = value;
    }

    /**
     * Gets the value of the crossSection property.
     * 
     * @return
     *     possible object is
     *     {@link CrossSection }
     *     
     */
    public CrossSection getCrossSection() {
        return crossSection;
    }

    /**
     * Sets the value of the crossSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossSection }
     *     
     */
    public void setCrossSection(CrossSection value) {
        this.crossSection = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the endfmt property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getENDFMT() {
        return endfmt;
    }

    /**
     * Sets the value of the endfmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setENDFMT(BigInteger value) {
        this.endfmt = value;
    }

}
