//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="XYs1d" type="{}xData_XYs1d_primary"/>
 *         &lt;element name="regions1d" type="{}xData_regions_1d_primary"/>
 *         &lt;element name="resonancesWithBackground" type="{}resonancesWithBackground"/>
 *         &lt;element name="reference" type="{}xlink"/>
 *         &lt;element name="CoulombElasticReference" type="{}xlink"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xYs1DOrRegions1DOrResonancesWithBackground"
})
@XmlRootElement(name = "crossSection")
public class CrossSection {

    @XmlElementRefs({
        @XmlElementRef(name = "reference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "XYs1d", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "CoulombElasticReference", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "resonancesWithBackground", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "regions1d", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> xYs1DOrRegions1DOrResonancesWithBackground;

    /**
     * Gets the value of the xYs1DOrRegions1DOrResonancesWithBackground property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xYs1DOrRegions1DOrResonancesWithBackground property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXYs1DOrRegions1DOrResonancesWithBackground().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Xlink }{@code >}
     * {@link JAXBElement }{@code <}{@link XDataXYs1DPrimary }{@code >}
     * {@link JAXBElement }{@code <}{@link Xlink }{@code >}
     * {@link JAXBElement }{@code <}{@link ResonancesWithBackground }{@code >}
     * {@link JAXBElement }{@code <}{@link XDataRegions1DPrimary }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getXYs1DOrRegions1DOrResonancesWithBackground() {
        if (xYs1DOrRegions1DOrResonancesWithBackground == null) {
            xYs1DOrRegions1DOrResonancesWithBackground = new ArrayList<JAXBElement<?>>();
        }
        return this.xYs1DOrRegions1DOrResonancesWithBackground;
    }

}
