//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CoulombElastic" type="{}CoulombElastic"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coulombElastic"
})
@XmlRootElement(name = "dCrossSection_dOmega")
public class DCrossSectionDOmega {

    @XmlElement(name = "CoulombElastic", required = true)
    protected CoulombElastic coulombElastic;

    /**
     * Gets the value of the coulombElastic property.
     * 
     * @return
     *     possible object is
     *     {@link CoulombElastic }
     *     
     */
    public CoulombElastic getCoulombElastic() {
        return coulombElastic;
    }

    /**
     * Sets the value of the coulombElastic property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoulombElastic }
     *     
     */
    public void setCoulombElastic(CoulombElastic value) {
        this.coulombElastic = value;
    }

}
