//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for distribution complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="distribution">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="angularTwoBody" type="{}angularTwoBody"/>
 *         &lt;element name="uncorrelated" type="{}uncorrelated"/>
 *         &lt;element name="angularEnergy" type="{}angularEnergy"/>
 *         &lt;element name="energyAngular" type="{}energyAngular"/>
 *         &lt;element name="KalbachMann" type="{}KalbachMann"/>
 *         &lt;element name="reference" type="{}xlink"/>
 *         &lt;element name="CoulombElasticReference" type="{}xlink"/>
 *         &lt;element name="coherentScattering" type="{}coherentScattering"/>
 *         &lt;element name="incoherentScattering" type="{}incoherentScattering"/>
 *         &lt;element name="unknown" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="unspecified" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "distribution", propOrder = {
    "angularTwoBody",
    "uncorrelated",
    "angularEnergy",
    "energyAngular",
    "kalbachMann",
    "reference",
    "coulombElasticReference",
    "coherentScattering",
    "incoherentScattering",
    "unknown",
    "unspecified"
})
public class Distribution {

    protected AngularTwoBody angularTwoBody;
    protected Uncorrelated uncorrelated;
    protected AngularEnergy angularEnergy;
    protected EnergyAngular energyAngular;
    @XmlElement(name = "KalbachMann")
    protected KalbachMann kalbachMann;
    protected Xlink reference;
    @XmlElement(name = "CoulombElasticReference")
    protected Xlink coulombElasticReference;
    protected CoherentScattering coherentScattering;
    protected IncoherentScattering incoherentScattering;
    protected Object unknown;
    protected Object unspecified;

    /**
     * Gets the value of the angularTwoBody property.
     * 
     * @return
     *     possible object is
     *     {@link AngularTwoBody }
     *     
     */
    public AngularTwoBody getAngularTwoBody() {
        return angularTwoBody;
    }

    /**
     * Sets the value of the angularTwoBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngularTwoBody }
     *     
     */
    public void setAngularTwoBody(AngularTwoBody value) {
        this.angularTwoBody = value;
    }

    /**
     * Gets the value of the uncorrelated property.
     * 
     * @return
     *     possible object is
     *     {@link Uncorrelated }
     *     
     */
    public Uncorrelated getUncorrelated() {
        return uncorrelated;
    }

    /**
     * Sets the value of the uncorrelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uncorrelated }
     *     
     */
    public void setUncorrelated(Uncorrelated value) {
        this.uncorrelated = value;
    }

    /**
     * Gets the value of the angularEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link AngularEnergy }
     *     
     */
    public AngularEnergy getAngularEnergy() {
        return angularEnergy;
    }

    /**
     * Sets the value of the angularEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngularEnergy }
     *     
     */
    public void setAngularEnergy(AngularEnergy value) {
        this.angularEnergy = value;
    }

    /**
     * Gets the value of the energyAngular property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyAngular }
     *     
     */
    public EnergyAngular getEnergyAngular() {
        return energyAngular;
    }

    /**
     * Sets the value of the energyAngular property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyAngular }
     *     
     */
    public void setEnergyAngular(EnergyAngular value) {
        this.energyAngular = value;
    }

    /**
     * Gets the value of the kalbachMann property.
     * 
     * @return
     *     possible object is
     *     {@link KalbachMann }
     *     
     */
    public KalbachMann getKalbachMann() {
        return kalbachMann;
    }

    /**
     * Sets the value of the kalbachMann property.
     * 
     * @param value
     *     allowed object is
     *     {@link KalbachMann }
     *     
     */
    public void setKalbachMann(KalbachMann value) {
        this.kalbachMann = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Xlink }
     *     
     */
    public Xlink getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xlink }
     *     
     */
    public void setReference(Xlink value) {
        this.reference = value;
    }

    /**
     * Gets the value of the coulombElasticReference property.
     * 
     * @return
     *     possible object is
     *     {@link Xlink }
     *     
     */
    public Xlink getCoulombElasticReference() {
        return coulombElasticReference;
    }

    /**
     * Sets the value of the coulombElasticReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xlink }
     *     
     */
    public void setCoulombElasticReference(Xlink value) {
        this.coulombElasticReference = value;
    }

    /**
     * Gets the value of the coherentScattering property.
     * 
     * @return
     *     possible object is
     *     {@link CoherentScattering }
     *     
     */
    public CoherentScattering getCoherentScattering() {
        return coherentScattering;
    }

    /**
     * Sets the value of the coherentScattering property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoherentScattering }
     *     
     */
    public void setCoherentScattering(CoherentScattering value) {
        this.coherentScattering = value;
    }

    /**
     * Gets the value of the incoherentScattering property.
     * 
     * @return
     *     possible object is
     *     {@link IncoherentScattering }
     *     
     */
    public IncoherentScattering getIncoherentScattering() {
        return incoherentScattering;
    }

    /**
     * Sets the value of the incoherentScattering property.
     * 
     * @param value
     *     allowed object is
     *     {@link IncoherentScattering }
     *     
     */
    public void setIncoherentScattering(IncoherentScattering value) {
        this.incoherentScattering = value;
    }

    /**
     * Gets the value of the unknown property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUnknown() {
        return unknown;
    }

    /**
     * Sets the value of the unknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUnknown(Object value) {
        this.unknown = value;
    }

    /**
     * Gets the value of the unspecified property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUnspecified() {
        return unspecified;
    }

    /**
     * Sets the value of the unspecified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUnspecified(Object value) {
        this.unspecified = value;
    }

}
