//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for energy_uncorrelated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="energy_uncorrelated">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="XYs2d" type="{}xData_XYs2d_primary"/>
 *         &lt;element name="regions2d" type="{}xData_regions_2d_primary"/>
 *         &lt;element name="generalEvaporation" type="{}generalEvaporation"/>
 *         &lt;element name="discreteGamma" type="{}discreteGamma"/>
 *         &lt;element name="NBodyPhaseSpace" type="{}NBodyPhaseSpace"/>
 *         &lt;element name="primaryGamma" type="{}primaryGamma"/>
 *         &lt;element name="evaporation" type="{}evaporation"/>
 *         &lt;element name="weightedFunctionals" type="{}weightedFunctionals"/>
 *         &lt;element name="simpleMaxwellianFission" type="{}simpleMaxwellianFission"/>
 *         &lt;element name="Watt" type="{}Watt"/>
 *         &lt;element name="MadlandNix" type="{}MadlandNix"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "energy_uncorrelated", propOrder = {
    "xYs2D",
    "regions2D",
    "generalEvaporation",
    "discreteGamma",
    "nBodyPhaseSpace",
    "primaryGamma",
    "evaporation",
    "weightedFunctionals",
    "simpleMaxwellianFission",
    "watt",
    "madlandNix"
})
public class EnergyUncorrelated {

    @XmlElement(name = "XYs2d")
    protected XDataXYs2DPrimary xYs2D;
    @XmlElement(name = "regions2d")
    protected XDataRegions2DPrimary regions2D;
    protected GeneralEvaporation generalEvaporation;
    protected DiscreteGamma discreteGamma;
    @XmlElement(name = "NBodyPhaseSpace")
    protected NBodyPhaseSpace nBodyPhaseSpace;
    protected PrimaryGamma primaryGamma;
    protected Evaporation evaporation;
    protected WeightedFunctionals weightedFunctionals;
    protected SimpleMaxwellianFission simpleMaxwellianFission;
    @XmlElement(name = "Watt")
    protected Watt watt;
    @XmlElement(name = "MadlandNix")
    protected MadlandNix madlandNix;

    /**
     * Gets the value of the xYs2D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataXYs2DPrimary }
     *     
     */
    public XDataXYs2DPrimary getXYs2D() {
        return xYs2D;
    }

    /**
     * Sets the value of the xYs2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataXYs2DPrimary }
     *     
     */
    public void setXYs2D(XDataXYs2DPrimary value) {
        this.xYs2D = value;
    }

    /**
     * Gets the value of the regions2D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataRegions2DPrimary }
     *     
     */
    public XDataRegions2DPrimary getRegions2D() {
        return regions2D;
    }

    /**
     * Sets the value of the regions2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataRegions2DPrimary }
     *     
     */
    public void setRegions2D(XDataRegions2DPrimary value) {
        this.regions2D = value;
    }

    /**
     * Gets the value of the generalEvaporation property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralEvaporation }
     *     
     */
    public GeneralEvaporation getGeneralEvaporation() {
        return generalEvaporation;
    }

    /**
     * Sets the value of the generalEvaporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralEvaporation }
     *     
     */
    public void setGeneralEvaporation(GeneralEvaporation value) {
        this.generalEvaporation = value;
    }

    /**
     * Gets the value of the discreteGamma property.
     * 
     * @return
     *     possible object is
     *     {@link DiscreteGamma }
     *     
     */
    public DiscreteGamma getDiscreteGamma() {
        return discreteGamma;
    }

    /**
     * Sets the value of the discreteGamma property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscreteGamma }
     *     
     */
    public void setDiscreteGamma(DiscreteGamma value) {
        this.discreteGamma = value;
    }

    /**
     * Gets the value of the nBodyPhaseSpace property.
     * 
     * @return
     *     possible object is
     *     {@link NBodyPhaseSpace }
     *     
     */
    public NBodyPhaseSpace getNBodyPhaseSpace() {
        return nBodyPhaseSpace;
    }

    /**
     * Sets the value of the nBodyPhaseSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link NBodyPhaseSpace }
     *     
     */
    public void setNBodyPhaseSpace(NBodyPhaseSpace value) {
        this.nBodyPhaseSpace = value;
    }

    /**
     * Gets the value of the primaryGamma property.
     * 
     * @return
     *     possible object is
     *     {@link PrimaryGamma }
     *     
     */
    public PrimaryGamma getPrimaryGamma() {
        return primaryGamma;
    }

    /**
     * Sets the value of the primaryGamma property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrimaryGamma }
     *     
     */
    public void setPrimaryGamma(PrimaryGamma value) {
        this.primaryGamma = value;
    }

    /**
     * Gets the value of the evaporation property.
     * 
     * @return
     *     possible object is
     *     {@link Evaporation }
     *     
     */
    public Evaporation getEvaporation() {
        return evaporation;
    }

    /**
     * Sets the value of the evaporation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Evaporation }
     *     
     */
    public void setEvaporation(Evaporation value) {
        this.evaporation = value;
    }

    /**
     * Gets the value of the weightedFunctionals property.
     * 
     * @return
     *     possible object is
     *     {@link WeightedFunctionals }
     *     
     */
    public WeightedFunctionals getWeightedFunctionals() {
        return weightedFunctionals;
    }

    /**
     * Sets the value of the weightedFunctionals property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightedFunctionals }
     *     
     */
    public void setWeightedFunctionals(WeightedFunctionals value) {
        this.weightedFunctionals = value;
    }

    /**
     * Gets the value of the simpleMaxwellianFission property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleMaxwellianFission }
     *     
     */
    public SimpleMaxwellianFission getSimpleMaxwellianFission() {
        return simpleMaxwellianFission;
    }

    /**
     * Sets the value of the simpleMaxwellianFission property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleMaxwellianFission }
     *     
     */
    public void setSimpleMaxwellianFission(SimpleMaxwellianFission value) {
        this.simpleMaxwellianFission = value;
    }

    /**
     * Gets the value of the watt property.
     * 
     * @return
     *     possible object is
     *     {@link Watt }
     *     
     */
    public Watt getWatt() {
        return watt;
    }

    /**
     * Sets the value of the watt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Watt }
     *     
     */
    public void setWatt(Watt value) {
        this.watt = value;
    }

    /**
     * Gets the value of the madlandNix property.
     * 
     * @return
     *     possible object is
     *     {@link MadlandNix }
     *     
     */
    public MadlandNix getMadlandNix() {
        return madlandNix;
    }

    /**
     * Sets the value of the madlandNix property.
     * 
     * @param value
     *     allowed object is
     *     {@link MadlandNix }
     *     
     */
    public void setMadlandNix(MadlandNix value) {
        this.madlandNix = value;
    }

}
