//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fissionEnergyReleased complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fissionEnergyReleased">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="promptProductKE" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="promptNeutronKE" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="delayedNeutronKE" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="promptGammaEnergy" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="delayedGammaEnergy" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="delayedBetaEnergy" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="neutrinoEnergy" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="nonNeutrinoEnergy" type="{}fissionEnergyReleaseSubform"/>
 *         &lt;element name="totalEnergy" type="{}fissionEnergyReleaseSubform"/>
 *       &lt;/sequence>
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fissionEnergyReleased", propOrder = {
    "promptProductKE",
    "promptNeutronKE",
    "delayedNeutronKE",
    "promptGammaEnergy",
    "delayedGammaEnergy",
    "delayedBetaEnergy",
    "neutrinoEnergy",
    "nonNeutrinoEnergy",
    "totalEnergy"
})
public class FissionEnergyReleased {

    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform promptProductKE;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform promptNeutronKE;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform delayedNeutronKE;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform promptGammaEnergy;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform delayedGammaEnergy;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform delayedBetaEnergy;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform neutrinoEnergy;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform nonNeutrinoEnergy;
    @XmlElement(required = true)
    protected FissionEnergyReleaseSubform totalEnergy;
    @XmlAttribute(name = "label", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String label;

    /**
     * Gets the value of the promptProductKE property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getPromptProductKE() {
        return promptProductKE;
    }

    /**
     * Sets the value of the promptProductKE property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setPromptProductKE(FissionEnergyReleaseSubform value) {
        this.promptProductKE = value;
    }

    /**
     * Gets the value of the promptNeutronKE property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getPromptNeutronKE() {
        return promptNeutronKE;
    }

    /**
     * Sets the value of the promptNeutronKE property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setPromptNeutronKE(FissionEnergyReleaseSubform value) {
        this.promptNeutronKE = value;
    }

    /**
     * Gets the value of the delayedNeutronKE property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getDelayedNeutronKE() {
        return delayedNeutronKE;
    }

    /**
     * Sets the value of the delayedNeutronKE property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setDelayedNeutronKE(FissionEnergyReleaseSubform value) {
        this.delayedNeutronKE = value;
    }

    /**
     * Gets the value of the promptGammaEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getPromptGammaEnergy() {
        return promptGammaEnergy;
    }

    /**
     * Sets the value of the promptGammaEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setPromptGammaEnergy(FissionEnergyReleaseSubform value) {
        this.promptGammaEnergy = value;
    }

    /**
     * Gets the value of the delayedGammaEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getDelayedGammaEnergy() {
        return delayedGammaEnergy;
    }

    /**
     * Sets the value of the delayedGammaEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setDelayedGammaEnergy(FissionEnergyReleaseSubform value) {
        this.delayedGammaEnergy = value;
    }

    /**
     * Gets the value of the delayedBetaEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getDelayedBetaEnergy() {
        return delayedBetaEnergy;
    }

    /**
     * Sets the value of the delayedBetaEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setDelayedBetaEnergy(FissionEnergyReleaseSubform value) {
        this.delayedBetaEnergy = value;
    }

    /**
     * Gets the value of the neutrinoEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getNeutrinoEnergy() {
        return neutrinoEnergy;
    }

    /**
     * Sets the value of the neutrinoEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setNeutrinoEnergy(FissionEnergyReleaseSubform value) {
        this.neutrinoEnergy = value;
    }

    /**
     * Gets the value of the nonNeutrinoEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getNonNeutrinoEnergy() {
        return nonNeutrinoEnergy;
    }

    /**
     * Sets the value of the nonNeutrinoEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setNonNeutrinoEnergy(FissionEnergyReleaseSubform value) {
        this.nonNeutrinoEnergy = value;
    }

    /**
     * Gets the value of the totalEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public FissionEnergyReleaseSubform getTotalEnergy() {
        return totalEnergy;
    }

    /**
     * Sets the value of the totalEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleaseSubform }
     *     
     */
    public void setTotalEnergy(FissionEnergyReleaseSubform value) {
        this.totalEnergy = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

}
