//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KalbachMann_subform complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KalbachMann_subform">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XYs2d" type="{}xData_XYs2d_primary"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KalbachMann_subform", propOrder = {
    "xYs2D"
})
public class KalbachMannSubform {

    @XmlElement(name = "XYs2d", required = true)
    protected XDataXYs2DPrimary xYs2D;

    /**
     * Gets the value of the xYs2D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataXYs2DPrimary }
     *     
     */
    public XDataXYs2DPrimary getXYs2D() {
        return xYs2D;
    }

    /**
     * Sets the value of the xYs2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataXYs2DPrimary }
     *     
     */
    public void setXYs2D(XDataXYs2DPrimary value) {
        this.xYs2D = value;
    }

}
