//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MadlandNix complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MadlandNix">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EFL" type="{}PhysicalQuantity"/>
 *         &lt;element name="EFH" type="{}PhysicalQuantity"/>
 *         &lt;element name="T_M" type="{}energyFunctionalData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MadlandNix", propOrder = {
    "efl",
    "efh",
    "tm"
})
public class MadlandNix {

    @XmlElement(name = "EFL", required = true)
    protected PhysicalQuantity efl;
    @XmlElement(name = "EFH", required = true)
    protected PhysicalQuantity efh;
    @XmlElement(name = "T_M", required = true)
    protected EnergyFunctionalData tm;

    /**
     * Gets the value of the efl property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalQuantity }
     *     
     */
    public PhysicalQuantity getEFL() {
        return efl;
    }

    /**
     * Sets the value of the efl property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalQuantity }
     *     
     */
    public void setEFL(PhysicalQuantity value) {
        this.efl = value;
    }

    /**
     * Gets the value of the efh property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalQuantity }
     *     
     */
    public PhysicalQuantity getEFH() {
        return efh;
    }

    /**
     * Sets the value of the efh property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalQuantity }
     *     
     */
    public void setEFH(PhysicalQuantity value) {
        this.efh = value;
    }

    /**
     * Gets the value of the tm property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyFunctionalData }
     *     
     */
    public EnergyFunctionalData getTM() {
        return tm;
    }

    /**
     * Sets the value of the tm property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyFunctionalData }
     *     
     */
    public void setTM(EnergyFunctionalData value) {
        this.tm = value;
    }

}
