//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multiplicity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multiplicity">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="constant1d" type="{}xData_constant1d"/>
 *         &lt;element name="XYs1d" type="{}xData_XYs1d_primary"/>
 *         &lt;element name="regions1d" type="{}xData_regions_1d_primary"/>
 *         &lt;element name="polynomial1d" type="{}xData_polynomial_1d_primary"/>
 *         &lt;element name="reference" type="{}xlink"/>
 *         &lt;element ref="{}weightedReference"/>
 *         &lt;element name="unknown" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiplicity", propOrder = {
    "constant1D",
    "xYs1D",
    "regions1D",
    "polynomial1D",
    "reference",
    "weightedReference",
    "unknown"
})
public class Multiplicity {

    @XmlElement(name = "constant1d")
    protected XDataConstant1D constant1D;
    @XmlElement(name = "XYs1d")
    protected XDataXYs1DPrimary xYs1D;
    @XmlElement(name = "regions1d")
    protected XDataRegions1DPrimary regions1D;
    @XmlElement(name = "polynomial1d")
    protected XDataPolynomial1DPrimary polynomial1D;
    protected Xlink reference;
    protected WeightedReference weightedReference;
    protected Object unknown;

    /**
     * Gets the value of the constant1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataConstant1D }
     *     
     */
    public XDataConstant1D getConstant1D() {
        return constant1D;
    }

    /**
     * Sets the value of the constant1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataConstant1D }
     *     
     */
    public void setConstant1D(XDataConstant1D value) {
        this.constant1D = value;
    }

    /**
     * Gets the value of the xYs1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataXYs1DPrimary }
     *     
     */
    public XDataXYs1DPrimary getXYs1D() {
        return xYs1D;
    }

    /**
     * Sets the value of the xYs1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataXYs1DPrimary }
     *     
     */
    public void setXYs1D(XDataXYs1DPrimary value) {
        this.xYs1D = value;
    }

    /**
     * Gets the value of the regions1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataRegions1DPrimary }
     *     
     */
    public XDataRegions1DPrimary getRegions1D() {
        return regions1D;
    }

    /**
     * Sets the value of the regions1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataRegions1DPrimary }
     *     
     */
    public void setRegions1D(XDataRegions1DPrimary value) {
        this.regions1D = value;
    }

    /**
     * Gets the value of the polynomial1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataPolynomial1DPrimary }
     *     
     */
    public XDataPolynomial1DPrimary getPolynomial1D() {
        return polynomial1D;
    }

    /**
     * Sets the value of the polynomial1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataPolynomial1DPrimary }
     *     
     */
    public void setPolynomial1D(XDataPolynomial1DPrimary value) {
        this.polynomial1D = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Xlink }
     *     
     */
    public Xlink getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xlink }
     *     
     */
    public void setReference(Xlink value) {
        this.reference = value;
    }

    /**
     * Gets the value of the weightedReference property.
     * 
     * @return
     *     possible object is
     *     {@link WeightedReference }
     *     
     */
    public WeightedReference getWeightedReference() {
        return weightedReference;
    }

    /**
     * Sets the value of the weightedReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightedReference }
     *     
     */
    public void setWeightedReference(WeightedReference value) {
        this.weightedReference = value;
    }

    /**
     * Gets the value of the unknown property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getUnknown() {
        return unknown;
    }

    /**
     * Sets the value of the unknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setUnknown(Object value) {
        this.unknown = value;
    }

}
