//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gnd_jax.GND package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CrossSectionReference_QNAME = new QName("", "reference");
    private final static QName _CrossSectionResonancesWithBackground_QNAME = new QName("", "resonancesWithBackground");
    private final static QName _CrossSectionCoulombElasticReference_QNAME = new QName("", "CoulombElasticReference");
    private final static QName _CrossSectionXYs1D_QNAME = new QName("", "XYs1d");
    private final static QName _CrossSectionRegions1D_QNAME = new QName("", "regions1d");
    private final static QName _SummandsAdd_QNAME = new QName("", "add");
    private final static QName _SummandsSubtract_QNAME = new QName("", "subtract");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gnd_jax.GND
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RMatrixLimited }
     * 
     */
    public RMatrixLimited createRMatrixLimited() {
        return new RMatrixLimited();
    }

    /**
     * Create an instance of {@link PoPsDecays }
     * 
     */
    public PoPsDecays createPoPsDecays() {
        return new PoPsDecays();
    }

    /**
     * Create an instance of {@link PoPsDecayProducts }
     * 
     */
    public PoPsDecayProducts createPoPsDecayProducts() {
        return new PoPsDecayProducts();
    }

    /**
     * Create an instance of {@link NuclearPlusCoulombInterference }
     * 
     */
    public NuclearPlusCoulombInterference createNuclearPlusCoulombInterference() {
        return new NuclearPlusCoulombInterference();
    }

    /**
     * Create an instance of {@link Ldependent }
     * 
     */
    public Ldependent createLdependent() {
        return new Ldependent();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link Axes }
     * 
     */
    public Axes createAxes() {
        return new Axes();
    }

    /**
     * Create an instance of {@link WeightedFunctionals }
     * 
     */
    public WeightedFunctionals createWeightedFunctionals() {
        return new WeightedFunctionals();
    }

    /**
     * Create an instance of {@link FissionComponentOutputChannel }
     * 
     */
    public FissionComponentOutputChannel createFissionComponentOutputChannel() {
        return new FissionComponentOutputChannel();
    }

    /**
     * Create an instance of {@link CoulombElastic }
     * 
     */
    public CoulombElastic createCoulombElastic() {
        return new CoulombElastic();
    }

    /**
     * Create an instance of {@link Sums }
     * 
     */
    public Sums createSums() {
        return new Sums();
    }

    /**
     * Create an instance of {@link Resolved }
     * 
     */
    public Resolved createResolved() {
        return new Resolved();
    }

    /**
     * Create an instance of {@link Aliases }
     * 
     */
    public Aliases createAliases() {
        return new Aliases();
    }

    /**
     * Create an instance of {@link Styles }
     * 
     */
    public Styles createStyles() {
        return new Styles();
    }

    /**
     * Create an instance of {@link OutputChannel }
     * 
     */
    public OutputChannel createOutputChannel() {
        return new OutputChannel();
    }

    /**
     * Create an instance of {@link gnd_jax.GND.Product }
     * 
     */
    public gnd_jax.GND.Product createProduct() {
        return new gnd_jax.GND.Product();
    }

    /**
     * Create an instance of {@link Documentations }
     * 
     */
    public Documentations createDocumentations() {
        return new Documentations();
    }

    /**
     * Create an instance of {@link Multiplicity }
     * 
     */
    public Multiplicity createMultiplicity() {
        return new Multiplicity();
    }

    /**
     * Create an instance of {@link Distribution }
     * 
     */
    public Distribution createDistribution() {
        return new Distribution();
    }

    /**
     * Create an instance of {@link AverageProductEnergy }
     * 
     */
    public AverageProductEnergy createAverageProductEnergy() {
        return new AverageProductEnergy();
    }

    /**
     * Create an instance of {@link ReactionSuite }
     * 
     */
    public ReactionSuite createReactionSuite() {
        return new ReactionSuite();
    }

    /**
     * Create an instance of {@link PoPs }
     * 
     */
    public PoPs createPoPs() {
        return new PoPs();
    }

    /**
     * Create an instance of {@link GaugeBosons }
     * 
     */
    public GaugeBosons createGaugeBosons() {
        return new GaugeBosons();
    }

    /**
     * Create an instance of {@link Leptons }
     * 
     */
    public Leptons createLeptons() {
        return new Leptons();
    }

    /**
     * Create an instance of {@link Baryons }
     * 
     */
    public Baryons createBaryons() {
        return new Baryons();
    }

    /**
     * Create an instance of {@link ChemicalElements }
     * 
     */
    public ChemicalElements createChemicalElements() {
        return new ChemicalElements();
    }

    /**
     * Create an instance of {@link Resonances }
     * 
     */
    public Resonances createResonances() {
        return new Resonances();
    }

    /**
     * Create an instance of {@link ScatteringRadius }
     * 
     */
    public ScatteringRadius createScatteringRadius() {
        return new ScatteringRadius();
    }

    /**
     * Create an instance of {@link Unresolved }
     * 
     */
    public Unresolved createUnresolved() {
        return new Unresolved();
    }

    /**
     * Create an instance of {@link Reactions }
     * 
     */
    public Reactions createReactions() {
        return new Reactions();
    }

    /**
     * Create an instance of {@link FissionComponents }
     * 
     */
    public FissionComponents createFissionComponents() {
        return new FissionComponents();
    }

    /**
     * Create an instance of {@link Productions }
     * 
     */
    public Productions createProductions() {
        return new Productions();
    }

    /**
     * Create an instance of {@link Reaction }
     * 
     */
    public Reaction createReaction() {
        return new Reaction();
    }

    /**
     * Create an instance of {@link Documentation }
     * 
     */
    public Documentation createDocumentation() {
        return new Documentation();
    }

    /**
     * Create an instance of {@link DCrossSectionDOmega }
     * 
     */
    public DCrossSectionDOmega createDCrossSectionDOmega() {
        return new DCrossSectionDOmega();
    }

    /**
     * Create an instance of {@link CrossSection }
     * 
     */
    public CrossSection createCrossSection() {
        return new CrossSection();
    }

    /**
     * Create an instance of {@link XDataXYs1DPrimary }
     * 
     */
    public XDataXYs1DPrimary createXDataXYs1DPrimary() {
        return new XDataXYs1DPrimary();
    }

    /**
     * Create an instance of {@link XDataRegions1DPrimary }
     * 
     */
    public XDataRegions1DPrimary createXDataRegions1DPrimary() {
        return new XDataRegions1DPrimary();
    }

    /**
     * Create an instance of {@link ResonancesWithBackground }
     * 
     */
    public ResonancesWithBackground createResonancesWithBackground() {
        return new ResonancesWithBackground();
    }

    /**
     * Create an instance of {@link Xlink }
     * 
     */
    public Xlink createXlink() {
        return new Xlink();
    }

    /**
     * Create an instance of {@link Production }
     * 
     */
    public Production createProduction() {
        return new Production();
    }

    /**
     * Create an instance of {@link FissionComponent }
     * 
     */
    public FissionComponent createFissionComponent() {
        return new FissionComponent();
    }

    /**
     * Create an instance of {@link WeightedReference }
     * 
     */
    public WeightedReference createWeightedReference() {
        return new WeightedReference();
    }

    /**
     * Create an instance of {@link RMLSpinGroup }
     * 
     */
    public RMLSpinGroup createRMLSpinGroup() {
        return new RMLSpinGroup();
    }

    /**
     * Create an instance of {@link URRConstantWidths }
     * 
     */
    public URRConstantWidths createURRConstantWidths() {
        return new URRConstantWidths();
    }

    /**
     * Create an instance of {@link CoherentScatteringSubform }
     * 
     */
    public CoherentScatteringSubform createCoherentScatteringSubform() {
        return new CoherentScatteringSubform();
    }

    /**
     * Create an instance of {@link PhysicalQuantity }
     * 
     */
    public PhysicalQuantity createPhysicalQuantity() {
        return new PhysicalQuantity();
    }

    /**
     * Create an instance of {@link ChemicalElement }
     * 
     */
    public ChemicalElement createChemicalElement() {
        return new ChemicalElement();
    }

    /**
     * Create an instance of {@link PoPsIsotope }
     * 
     */
    public PoPsIsotope createPoPsIsotope() {
        return new PoPsIsotope();
    }

    /**
     * Create an instance of {@link XDataRegions1D }
     * 
     */
    public XDataRegions1D createXDataRegions1D() {
        return new XDataRegions1D();
    }

    /**
     * Create an instance of {@link XDataXYs3DPrimary }
     * 
     */
    public XDataXYs3DPrimary createXDataXYs3DPrimary() {
        return new XDataXYs3DPrimary();
    }

    /**
     * Create an instance of {@link Unspecified }
     * 
     */
    public Unspecified createUnspecified() {
        return new Unspecified();
    }

    /**
     * Create an instance of {@link SingleLevelBreitWigner }
     * 
     */
    public SingleLevelBreitWigner createSingleLevelBreitWigner() {
        return new SingleLevelBreitWigner();
    }

    /**
     * Create an instance of {@link CrossSectionSum }
     * 
     */
    public CrossSectionSum createCrossSectionSum() {
        return new CrossSectionSum();
    }

    /**
     * Create an instance of {@link XDataXYs1D }
     * 
     */
    public XDataXYs1D createXDataXYs1D() {
        return new XDataXYs1D();
    }

    /**
     * Create an instance of {@link CoulombExpansionTerm }
     * 
     */
    public CoulombExpansionTerm createCoulombExpansionTerm() {
        return new CoulombExpansionTerm();
    }

    /**
     * Create an instance of {@link URRJSection }
     * 
     */
    public URRJSection createURRJSection() {
        return new URRJSection();
    }

    /**
     * Create an instance of {@link PQUDouble }
     * 
     */
    public PQUDouble createPQUDouble() {
        return new PQUDouble();
    }

    /**
     * Create an instance of {@link Evaporation }
     * 
     */
    public Evaporation createEvaporation() {
        return new Evaporation();
    }

    /**
     * Create an instance of {@link XDataValues }
     * 
     */
    public XDataValues createXDataValues() {
        return new XDataValues();
    }

    /**
     * Create an instance of {@link XDataXYs2D }
     * 
     */
    public XDataXYs2D createXDataXYs2D() {
        return new XDataXYs2D();
    }

    /**
     * Create an instance of {@link XDataUncertainty }
     * 
     */
    public XDataUncertainty createXDataUncertainty() {
        return new XDataUncertainty();
    }

    /**
     * Create an instance of {@link AngularEnergy }
     * 
     */
    public AngularEnergy createAngularEnergy() {
        return new AngularEnergy();
    }

    /**
     * Create an instance of {@link Unknown }
     * 
     */
    public Unknown createUnknown() {
        return new Unknown();
    }

    /**
     * Create an instance of {@link Q }
     * 
     */
    public Q createQ() {
        return new Q();
    }

    /**
     * Create an instance of {@link XDataXYs1DInRegions }
     * 
     */
    public XDataXYs1DInRegions createXDataXYs1DInRegions() {
        return new XDataXYs1DInRegions();
    }

    /**
     * Create an instance of {@link TabulatedWidths }
     * 
     */
    public TabulatedWidths createTabulatedWidths() {
        return new TabulatedWidths();
    }

    /**
     * Create an instance of {@link MultiLevelBreitWigner }
     * 
     */
    public MultiLevelBreitWigner createMultiLevelBreitWigner() {
        return new MultiLevelBreitWigner();
    }

    /**
     * Create an instance of {@link GeneralEvaporation }
     * 
     */
    public GeneralEvaporation createGeneralEvaporation() {
        return new GeneralEvaporation();
    }

    /**
     * Create an instance of {@link Forward }
     * 
     */
    public Forward createForward() {
        return new Forward();
    }

    /**
     * Create an instance of {@link ResonanceParameters }
     * 
     */
    public ResonanceParameters createResonanceParameters() {
        return new ResonanceParameters();
    }

    /**
     * Create an instance of {@link XDataRegions2D }
     * 
     */
    public XDataRegions2D createXDataRegions2D() {
        return new XDataRegions2D();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link ResonanceRegionQ }
     * 
     */
    public ResonanceRegionQ createResonanceRegionQ() {
        return new ResonanceRegionQ();
    }

    /**
     * Create an instance of {@link ConstantScatteringRadius }
     * 
     */
    public ConstantScatteringRadius createConstantScatteringRadius() {
        return new ConstantScatteringRadius();
    }

    /**
     * Create an instance of {@link XDataXYs2DInRegions }
     * 
     */
    public XDataXYs2DInRegions createXDataXYs2DInRegions() {
        return new XDataXYs2DInRegions();
    }

    /**
     * Create an instance of {@link DiscreteGamma }
     * 
     */
    public DiscreteGamma createDiscreteGamma() {
        return new DiscreteGamma();
    }

    /**
     * Create an instance of {@link Summands }
     * 
     */
    public Summands createSummands() {
        return new Summands();
    }

    /**
     * Create an instance of {@link RMLChannel }
     * 
     */
    public RMLChannel createRMLChannel() {
        return new RMLChannel();
    }

    /**
     * Create an instance of {@link FissionEnergyReleased }
     * 
     */
    public FissionEnergyReleased createFissionEnergyReleased() {
        return new FissionEnergyReleased();
    }

    /**
     * Create an instance of {@link PQUFraction }
     * 
     */
    public PQUFraction createPQUFraction() {
        return new PQUFraction();
    }

    /**
     * Create an instance of {@link XDataXYs3DInRegions }
     * 
     */
    public XDataXYs3DInRegions createXDataXYs3DInRegions() {
        return new XDataXYs3DInRegions();
    }

    /**
     * Create an instance of {@link IncoherentScattering }
     * 
     */
    public IncoherentScattering createIncoherentScattering() {
        return new IncoherentScattering();
    }

    /**
     * Create an instance of {@link EnergyFunctionalData }
     * 
     */
    public EnergyFunctionalData createEnergyFunctionalData() {
        return new EnergyFunctionalData();
    }

    /**
     * Create an instance of {@link CoulombExpansion }
     * 
     */
    public CoulombExpansion createCoulombExpansion() {
        return new CoulombExpansion();
    }

    /**
     * Create an instance of {@link Isotropic }
     * 
     */
    public Isotropic createIsotropic() {
        return new Isotropic();
    }

    /**
     * Create an instance of {@link FissionEnergyReleaseSubform }
     * 
     */
    public FissionEnergyReleaseSubform createFissionEnergyReleaseSubform() {
        return new FissionEnergyReleaseSubform();
    }

    /**
     * Create an instance of {@link NBodyPhaseSpace }
     * 
     */
    public NBodyPhaseSpace createNBodyPhaseSpace() {
        return new NBodyPhaseSpace();
    }

    /**
     * Create an instance of {@link ReichMoore }
     * 
     */
    public ReichMoore createReichMoore() {
        return new ReichMoore();
    }

    /**
     * Create an instance of {@link XDataLegendre1D }
     * 
     */
    public XDataLegendre1D createXDataLegendre1D() {
        return new XDataLegendre1D();
    }

    /**
     * Create an instance of {@link XDataRegions2DPrimary }
     * 
     */
    public XDataRegions2DPrimary createXDataRegions2DPrimary() {
        return new XDataRegions2DPrimary();
    }

    /**
     * Create an instance of {@link AngularTwoBody }
     * 
     */
    public AngularTwoBody createAngularTwoBody() {
        return new AngularTwoBody();
    }

    /**
     * Create an instance of {@link PoPsQuantity }
     * 
     */
    public PoPsQuantity createPoPsQuantity() {
        return new PoPsQuantity();
    }

    /**
     * Create an instance of {@link RMLChannels }
     * 
     */
    public RMLChannels createRMLChannels() {
        return new RMLChannels();
    }

    /**
     * Create an instance of {@link PoPsNuclearLevel }
     * 
     */
    public PoPsNuclearLevel createPoPsNuclearLevel() {
        return new PoPsNuclearLevel();
    }

    /**
     * Create an instance of {@link PQUString }
     * 
     */
    public PQUString createPQUString() {
        return new PQUString();
    }

    /**
     * Create an instance of {@link EnergyDependentWidths }
     * 
     */
    public EnergyDependentWidths createEnergyDependentWidths() {
        return new EnergyDependentWidths();
    }

    /**
     * Create an instance of {@link URRLSection }
     * 
     */
    public URRLSection createURRLSection() {
        return new URRLSection();
    }

    /**
     * Create an instance of {@link PoPsNucleus }
     * 
     */
    public PoPsNucleus createPoPsNucleus() {
        return new PoPsNucleus();
    }

    /**
     * Create an instance of {@link AngularUncorrelated }
     * 
     */
    public AngularUncorrelated createAngularUncorrelated() {
        return new AngularUncorrelated();
    }

    /**
     * Create an instance of {@link PQUInteger }
     * 
     */
    public PQUInteger createPQUInteger() {
        return new PQUInteger();
    }

    /**
     * Create an instance of {@link EnergyAngular }
     * 
     */
    public EnergyAngular createEnergyAngular() {
        return new EnergyAngular();
    }

    /**
     * Create an instance of {@link Watt }
     * 
     */
    public Watt createWatt() {
        return new Watt();
    }

    /**
     * Create an instance of {@link MultiplicitySum }
     * 
     */
    public MultiplicitySum createMultiplicitySum() {
        return new MultiplicitySum();
    }

    /**
     * Create an instance of {@link SimpleMaxwellianFission }
     * 
     */
    public SimpleMaxwellianFission createSimpleMaxwellianFission() {
        return new SimpleMaxwellianFission();
    }

    /**
     * Create an instance of {@link KalbachMannSubform }
     * 
     */
    public KalbachMannSubform createKalbachMannSubform() {
        return new KalbachMannSubform();
    }

    /**
     * Create an instance of {@link ResonanceReaction }
     * 
     */
    public ResonanceReaction createResonanceReaction() {
        return new ResonanceReaction();
    }

    /**
     * Create an instance of {@link Lepton }
     * 
     */
    public Lepton createLepton() {
        return new Lepton();
    }

    /**
     * Create an instance of {@link CoherentScattering }
     * 
     */
    public CoherentScattering createCoherentScattering() {
        return new CoherentScattering();
    }

    /**
     * Create an instance of {@link XDataRegions3DPrimary }
     * 
     */
    public XDataRegions3DPrimary createXDataRegions3DPrimary() {
        return new XDataRegions3DPrimary();
    }

    /**
     * Create an instance of {@link MadlandNix }
     * 
     */
    public MadlandNix createMadlandNix() {
        return new MadlandNix();
    }

    /**
     * Create an instance of {@link PoPsBasicParticle }
     * 
     */
    public PoPsBasicParticle createPoPsBasicParticle() {
        return new PoPsBasicParticle();
    }

    /**
     * Create an instance of {@link XDataPolynomial1DPrimary }
     * 
     */
    public XDataPolynomial1DPrimary createXDataPolynomial1DPrimary() {
        return new XDataPolynomial1DPrimary();
    }

    /**
     * Create an instance of {@link XDataXYs2DPrimary }
     * 
     */
    public XDataXYs2DPrimary createXDataXYs2DPrimary() {
        return new XDataXYs2DPrimary();
    }

    /**
     * Create an instance of {@link XDataConstant1D }
     * 
     */
    public XDataConstant1D createXDataConstant1D() {
        return new XDataConstant1D();
    }

    /**
     * Create an instance of {@link XDataUncertanties }
     * 
     */
    public XDataUncertanties createXDataUncertanties() {
        return new XDataUncertanties();
    }

    /**
     * Create an instance of {@link Uncorrelated }
     * 
     */
    public Uncorrelated createUncorrelated() {
        return new Uncorrelated();
    }

    /**
     * Create an instance of {@link ConstantQ }
     * 
     */
    public ConstantQ createConstantQ() {
        return new ConstantQ();
    }

    /**
     * Create an instance of {@link PrimaryGamma }
     * 
     */
    public PrimaryGamma createPrimaryGamma() {
        return new PrimaryGamma();
    }

    /**
     * Create an instance of {@link KalbachMann }
     * 
     */
    public KalbachMann createKalbachMann() {
        return new KalbachMann();
    }

    /**
     * Create an instance of {@link EnergyUncorrelated }
     * 
     */
    public EnergyUncorrelated createEnergyUncorrelated() {
        return new EnergyUncorrelated();
    }

    /**
     * Create an instance of {@link RMatrixLimited.ResonanceReactions }
     * 
     */
    public RMatrixLimited.ResonanceReactions createRMatrixLimitedResonanceReactions() {
        return new RMatrixLimited.ResonanceReactions();
    }

    /**
     * Create an instance of {@link PoPsDecays.Decay }
     * 
     */
    public PoPsDecays.Decay createPoPsDecaysDecay() {
        return new PoPsDecays.Decay();
    }

    /**
     * Create an instance of {@link PoPsDecayProducts.Product }
     * 
     */
    public PoPsDecayProducts.Product createPoPsDecayProductsProduct() {
        return new PoPsDecayProducts.Product();
    }

    /**
     * Create an instance of {@link NuclearPlusCoulombInterference.EffectiveCrossSection }
     * 
     */
    public NuclearPlusCoulombInterference.EffectiveCrossSection createNuclearPlusCoulombInterferenceEffectiveCrossSection() {
        return new NuclearPlusCoulombInterference.EffectiveCrossSection();
    }

    /**
     * Create an instance of {@link NuclearPlusCoulombInterference.EffectiveDistribution }
     * 
     */
    public NuclearPlusCoulombInterference.EffectiveDistribution createNuclearPlusCoulombInterferenceEffectiveDistribution() {
        return new NuclearPlusCoulombInterference.EffectiveDistribution();
    }

    /**
     * Create an instance of {@link Ldependent.Default }
     * 
     */
    public Ldependent.Default createLdependentDefault() {
        return new Ldependent.Default();
    }

    /**
     * Create an instance of {@link Ldependent.Lspecific }
     * 
     */
    public Ldependent.Lspecific createLdependentLspecific() {
        return new Ldependent.Lspecific();
    }

    /**
     * Create an instance of {@link Table.ColumnHeaders }
     * 
     */
    public Table.ColumnHeaders createTableColumnHeaders() {
        return new Table.ColumnHeaders();
    }

    /**
     * Create an instance of {@link Axes.Axis }
     * 
     */
    public Axes.Axis createAxesAxis() {
        return new Axes.Axis();
    }

    /**
     * Create an instance of {@link WeightedFunctionals.Weighted }
     * 
     */
    public WeightedFunctionals.Weighted createWeightedFunctionalsWeighted() {
        return new WeightedFunctionals.Weighted();
    }

    /**
     * Create an instance of {@link FissionComponentOutputChannel.Products }
     * 
     */
    public FissionComponentOutputChannel.Products createFissionComponentOutputChannelProducts() {
        return new FissionComponentOutputChannel.Products();
    }

    /**
     * Create an instance of {@link CoulombElastic.RutherfordScattering }
     * 
     */
    public CoulombElastic.RutherfordScattering createCoulombElasticRutherfordScattering() {
        return new CoulombElastic.RutherfordScattering();
    }

    /**
     * Create an instance of {@link Sums.CrossSections }
     * 
     */
    public Sums.CrossSections createSumsCrossSections() {
        return new Sums.CrossSections();
    }

    /**
     * Create an instance of {@link Sums.Multiplicities }
     * 
     */
    public Sums.Multiplicities createSumsMultiplicities() {
        return new Sums.Multiplicities();
    }

    /**
     * Create an instance of {@link Resolved.Region }
     * 
     */
    public Resolved.Region createResolvedRegion() {
        return new Resolved.Region();
    }

    /**
     * Create an instance of {@link Aliases.Alias }
     * 
     */
    public Aliases.Alias createAliasesAlias() {
        return new Aliases.Alias();
    }

    /**
     * Create an instance of {@link Aliases.MetaStable }
     * 
     */
    public Aliases.MetaStable createAliasesMetaStable() {
        return new Aliases.MetaStable();
    }

    /**
     * Create an instance of {@link Styles.Evaluated }
     * 
     */
    public Styles.Evaluated createStylesEvaluated() {
        return new Styles.Evaluated();
    }

    /**
     * Create an instance of {@link Styles.CrossSectionReconstructed }
     * 
     */
    public Styles.CrossSectionReconstructed createStylesCrossSectionReconstructed() {
        return new Styles.CrossSectionReconstructed();
    }

    /**
     * Create an instance of {@link Styles.Heated }
     * 
     */
    public Styles.Heated createStylesHeated() {
        return new Styles.Heated();
    }

    /**
     * Create an instance of {@link Styles.AverageProductData }
     * 
     */
    public Styles.AverageProductData createStylesAverageProductData() {
        return new Styles.AverageProductData();
    }

    /**
     * Create an instance of {@link OutputChannel.Products }
     * 
     */
    public OutputChannel.Products createOutputChannelProducts() {
        return new OutputChannel.Products();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Xlink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reference", scope = CrossSection.class)
    public JAXBElement<Xlink> createCrossSectionReference(Xlink value) {
        return new JAXBElement<Xlink>(_CrossSectionReference_QNAME, Xlink.class, CrossSection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResonancesWithBackground }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resonancesWithBackground", scope = CrossSection.class)
    public JAXBElement<ResonancesWithBackground> createCrossSectionResonancesWithBackground(ResonancesWithBackground value) {
        return new JAXBElement<ResonancesWithBackground>(_CrossSectionResonancesWithBackground_QNAME, ResonancesWithBackground.class, CrossSection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Xlink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CoulombElasticReference", scope = CrossSection.class)
    public JAXBElement<Xlink> createCrossSectionCoulombElasticReference(Xlink value) {
        return new JAXBElement<Xlink>(_CrossSectionCoulombElasticReference_QNAME, Xlink.class, CrossSection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XDataXYs1DPrimary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "XYs1d", scope = CrossSection.class)
    public JAXBElement<XDataXYs1DPrimary> createCrossSectionXYs1D(XDataXYs1DPrimary value) {
        return new JAXBElement<XDataXYs1DPrimary>(_CrossSectionXYs1D_QNAME, XDataXYs1DPrimary.class, CrossSection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XDataRegions1DPrimary }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "regions1d", scope = CrossSection.class)
    public JAXBElement<XDataRegions1DPrimary> createCrossSectionRegions1D(XDataRegions1DPrimary value) {
        return new JAXBElement<XDataRegions1DPrimary>(_CrossSectionRegions1D_QNAME, XDataRegions1DPrimary.class, CrossSection.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Xlink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "add", scope = Summands.class)
    public JAXBElement<Xlink> createSummandsAdd(Xlink value) {
        return new JAXBElement<Xlink>(_SummandsAdd_QNAME, Xlink.class, Summands.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Xlink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "subtract", scope = Summands.class)
    public JAXBElement<Xlink> createSummandsSubtract(Xlink value) {
        return new JAXBElement<Xlink>(_SummandsSubtract_QNAME, Xlink.class, Summands.class, value);
    }

}
