//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PoPs_basicParticle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoPs_basicParticle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mass" type="{}PoPs_quantity"/>
 *         &lt;element name="spin" type="{}PoPs_quantity"/>
 *         &lt;element name="parity" type="{}PoPs_quantity"/>
 *         &lt;element name="charge" type="{}PoPs_quantity"/>
 *         &lt;element name="halflife" type="{}PoPs_quantity"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoPs_basicParticle", propOrder = {
    "mass",
    "spin",
    "parity",
    "charge",
    "halflife"
})
@XmlSeeAlso({
    Lepton.class
})
public class PoPsBasicParticle {

    @XmlElement(required = true)
    protected PoPsQuantity mass;
    @XmlElement(required = true)
    protected PoPsQuantity spin;
    @XmlElement(required = true)
    protected PoPsQuantity parity;
    @XmlElement(required = true)
    protected PoPsQuantity charge;
    @XmlElement(required = true)
    protected PoPsQuantity halflife;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setMass(PoPsQuantity value) {
        this.mass = value;
    }

    /**
     * Gets the value of the spin property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getSpin() {
        return spin;
    }

    /**
     * Sets the value of the spin property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setSpin(PoPsQuantity value) {
        this.spin = value;
    }

    /**
     * Gets the value of the parity property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getParity() {
        return parity;
    }

    /**
     * Sets the value of the parity property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setParity(PoPsQuantity value) {
        this.parity = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setCharge(PoPsQuantity value) {
        this.charge = value;
    }

    /**
     * Gets the value of the halflife property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getHalflife() {
        return halflife;
    }

    /**
     * Sets the value of the halflife property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setHalflife(PoPsQuantity value) {
        this.halflife = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
