//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for PoPs_nuclearLevel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoPs_nuclearLevel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mass" type="{}PoPs_quantity" minOccurs="0"/>
 *         &lt;element name="spin" type="{}PoPs_quantity" minOccurs="0"/>
 *         &lt;element name="charge" type="{}PoPs_quantity"/>
 *         &lt;element name="nucleus" type="{}PoPs_nucleus"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoPs_nuclearLevel", propOrder = {
    "mass",
    "spin",
    "charge",
    "nucleus"
})
public class PoPsNuclearLevel {

    protected PoPsQuantity mass;
    protected PoPsQuantity spin;
    @XmlElement(required = true)
    protected PoPsQuantity charge;
    @XmlElement(required = true)
    protected PoPsNucleus nucleus;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String id;

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setMass(PoPsQuantity value) {
        this.mass = value;
    }

    /**
     * Gets the value of the spin property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getSpin() {
        return spin;
    }

    /**
     * Sets the value of the spin property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setSpin(PoPsQuantity value) {
        this.spin = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsQuantity }
     *     
     */
    public PoPsQuantity getCharge() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsQuantity }
     *     
     */
    public void setCharge(PoPsQuantity value) {
        this.charge = value;
    }

    /**
     * Gets the value of the nucleus property.
     * 
     * @return
     *     possible object is
     *     {@link PoPsNucleus }
     *     
     */
    public PoPsNucleus getNucleus() {
        return nucleus;
    }

    /**
     * Sets the value of the nucleus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPsNucleus }
     *     
     */
    public void setNucleus(PoPsNucleus value) {
        this.nucleus = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
