//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PoPs_decays complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoPs_decays">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="decay" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="probability" type="{}PoPs_quantity"/>
 *                   &lt;element name="products" type="{}PoPs_decayProducts"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoPs_decays", propOrder = {
    "decay"
})
public class PoPsDecays {

    @XmlElement(required = true)
    protected List<PoPsDecays.Decay> decay;

    /**
     * Gets the value of the decay property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the decay property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDecay().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoPsDecays.Decay }
     * 
     * 
     */
    public List<PoPsDecays.Decay> getDecay() {
        if (decay == null) {
            decay = new ArrayList<PoPsDecays.Decay>();
        }
        return this.decay;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="probability" type="{}PoPs_quantity"/>
     *         &lt;element name="products" type="{}PoPs_decayProducts"/>
     *       &lt;/sequence>
     *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "probability",
        "products"
    })
    public static class Decay {

        @XmlElement(required = true)
        protected PoPsQuantity probability;
        @XmlElement(required = true)
        protected PoPsDecayProducts products;
        @XmlAttribute(name = "label", required = true)
        protected String label;

        /**
         * Gets the value of the probability property.
         * 
         * @return
         *     possible object is
         *     {@link PoPsQuantity }
         *     
         */
        public PoPsQuantity getProbability() {
            return probability;
        }

        /**
         * Sets the value of the probability property.
         * 
         * @param value
         *     allowed object is
         *     {@link PoPsQuantity }
         *     
         */
        public void setProbability(PoPsQuantity value) {
            this.probability = value;
        }

        /**
         * Gets the value of the products property.
         * 
         * @return
         *     possible object is
         *     {@link PoPsDecayProducts }
         *     
         */
        public PoPsDecayProducts getProducts() {
            return products;
        }

        /**
         * Sets the value of the products property.
         * 
         * @param value
         *     allowed object is
         *     {@link PoPsDecayProducts }
         *     
         */
        public void setProducts(PoPsDecayProducts value) {
            this.products = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }

}
