//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for primaryGamma complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="primaryGamma">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="axes" type="{}axes"/>
 *       &lt;/sequence>
 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domainMin" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domainMax" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "primaryGamma", propOrder = {
    "axes"
})
public class PrimaryGamma {

    @XmlElement(required = true)
    protected Axes axes;
    @XmlAttribute(name = "value", required = true)
    protected double value;
    @XmlAttribute(name = "domainMin", required = true)
    protected double domainMin;
    @XmlAttribute(name = "domainMax", required = true)
    protected double domainMax;

    /**
     * Gets the value of the axes property.
     * 
     * @return
     *     possible object is
     *     {@link Axes }
     *     
     */
    public Axes getAxes() {
        return axes;
    }

    /**
     * Sets the value of the axes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Axes }
     *     
     */
    public void setAxes(Axes value) {
        this.axes = value;
    }

    /**
     * Gets the value of the value property.
     * 
     */
    public double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     */
    public void setValue(double value) {
        this.value = value;
    }

    /**
     * Gets the value of the domainMin property.
     * 
     */
    public double getDomainMin() {
        return domainMin;
    }

    /**
     * Sets the value of the domainMin property.
     * 
     */
    public void setDomainMin(double value) {
        this.domainMin = value;
    }

    /**
     * Gets the value of the domainMax property.
     * 
     */
    public double getDomainMax() {
        return domainMax;
    }

    /**
     * Sets the value of the domainMax property.
     * 
     */
    public void setDomainMax(double value) {
        this.domainMax = value;
    }

}
