//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="documentations" type="{}documentations" minOccurs="0"/>
 *         &lt;element name="multiplicity" type="{}multiplicity"/>
 *         &lt;element name="distribution" type="{}distribution"/>
 *         &lt;element name="outputChannel" type="{}outputChannel" minOccurs="0"/>
 *         &lt;element name="averageProductEnergy" type="{}averageProductEnergy" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="decayRate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="emissionMode" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="originationLevel" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ENDFconversionFlag" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentations",
    "multiplicity",
    "distribution",
    "outputChannel",
    "averageProductEnergy"
})
@XmlRootElement(name = "product")
public class Product {

    protected Documentations documentations;
    @XmlElement(required = true)
    protected Multiplicity multiplicity;
    @XmlElement(required = true)
    protected Distribution distribution;
    protected OutputChannel outputChannel;
    protected AverageProductEnergy averageProductEnergy;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "decayRate")
    @XmlSchemaType(name = "anySimpleType")
    protected String decayRate;
    @XmlAttribute(name = "emissionMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String emissionMode;
    @XmlAttribute(name = "originationLevel")
    @XmlSchemaType(name = "anySimpleType")
    protected String originationLevel;
    @XmlAttribute(name = "ENDFconversionFlag")
    @XmlSchemaType(name = "anySimpleType")
    protected String endFconversionFlag;

    /**
     * Gets the value of the documentations property.
     * 
     * @return
     *     possible object is
     *     {@link Documentations }
     *     
     */
    public Documentations getDocumentations() {
        return documentations;
    }

    /**
     * Sets the value of the documentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documentations }
     *     
     */
    public void setDocumentations(Documentations value) {
        this.documentations = value;
    }

    /**
     * Gets the value of the multiplicity property.
     * 
     * @return
     *     possible object is
     *     {@link Multiplicity }
     *     
     */
    public Multiplicity getMultiplicity() {
        return multiplicity;
    }

    /**
     * Sets the value of the multiplicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Multiplicity }
     *     
     */
    public void setMultiplicity(Multiplicity value) {
        this.multiplicity = value;
    }

    /**
     * Gets the value of the distribution property.
     * 
     * @return
     *     possible object is
     *     {@link Distribution }
     *     
     */
    public Distribution getDistribution() {
        return distribution;
    }

    /**
     * Sets the value of the distribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Distribution }
     *     
     */
    public void setDistribution(Distribution value) {
        this.distribution = value;
    }

    /**
     * Gets the value of the outputChannel property.
     * 
     * @return
     *     possible object is
     *     {@link OutputChannel }
     *     
     */
    public OutputChannel getOutputChannel() {
        return outputChannel;
    }

    /**
     * Sets the value of the outputChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputChannel }
     *     
     */
    public void setOutputChannel(OutputChannel value) {
        this.outputChannel = value;
    }

    /**
     * Gets the value of the averageProductEnergy property.
     * 
     * @return
     *     possible object is
     *     {@link AverageProductEnergy }
     *     
     */
    public AverageProductEnergy getAverageProductEnergy() {
        return averageProductEnergy;
    }

    /**
     * Sets the value of the averageProductEnergy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AverageProductEnergy }
     *     
     */
    public void setAverageProductEnergy(AverageProductEnergy value) {
        this.averageProductEnergy = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the decayRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecayRate() {
        return decayRate;
    }

    /**
     * Sets the value of the decayRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecayRate(String value) {
        this.decayRate = value;
    }

    /**
     * Gets the value of the emissionMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmissionMode() {
        return emissionMode;
    }

    /**
     * Sets the value of the emissionMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmissionMode(String value) {
        this.emissionMode = value;
    }

    /**
     * Gets the value of the originationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginationLevel() {
        return originationLevel;
    }

    /**
     * Sets the value of the originationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginationLevel(String value) {
        this.originationLevel = value;
    }

    /**
     * Gets the value of the endFconversionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDFconversionFlag() {
        return endFconversionFlag;
    }

    /**
     * Sets the value of the endFconversionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDFconversionFlag(String value) {
        this.endFconversionFlag = value;
    }

}
