//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Q complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Q">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="constant1d" type="{}xData_constant1d"/>
 *         &lt;element name="pointwise" type="{}xData_XYs1d"/>
 *         &lt;element name="fissionEnergyReleased" type="{}fissionEnergyReleased"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Q", propOrder = {
    "constant1D",
    "pointwise",
    "fissionEnergyReleased"
})
public class Q {

    @XmlElement(name = "constant1d")
    protected XDataConstant1D constant1D;
    protected XDataXYs1D pointwise;
    protected FissionEnergyReleased fissionEnergyReleased;

    /**
     * Gets the value of the constant1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataConstant1D }
     *     
     */
    public XDataConstant1D getConstant1D() {
        return constant1D;
    }

    /**
     * Sets the value of the constant1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataConstant1D }
     *     
     */
    public void setConstant1D(XDataConstant1D value) {
        this.constant1D = value;
    }

    /**
     * Gets the value of the pointwise property.
     * 
     * @return
     *     possible object is
     *     {@link XDataXYs1D }
     *     
     */
    public XDataXYs1D getPointwise() {
        return pointwise;
    }

    /**
     * Sets the value of the pointwise property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataXYs1D }
     *     
     */
    public void setPointwise(XDataXYs1D value) {
        this.pointwise = value;
    }

    /**
     * Gets the value of the fissionEnergyReleased property.
     * 
     * @return
     *     possible object is
     *     {@link FissionEnergyReleased }
     *     
     */
    public FissionEnergyReleased getFissionEnergyReleased() {
        return fissionEnergyReleased;
    }

    /**
     * Sets the value of the fissionEnergyReleased property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionEnergyReleased }
     *     
     */
    public void setFissionEnergyReleased(FissionEnergyReleased value) {
        this.fissionEnergyReleased = value;
    }

}
