//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="styles" type="{}styles"/>
 *         &lt;element name="documentations" type="{}documentations"/>
 *         &lt;element ref="{}PoPs"/>
 *         &lt;element ref="{}resonances" minOccurs="0"/>
 *         &lt;element name="reactions" type="{}reactions"/>
 *         &lt;element name="sums" type="{}sums" minOccurs="0"/>
 *         &lt;element name="fissionComponents" type="{}fissionComponents" minOccurs="0"/>
 *         &lt;element name="productions" type="{}productions" minOccurs="0"/>
 *         &lt;element name="applicationData" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="projectile" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="evaluation" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="projectileFrame" use="required" type="{}frame" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "styles",
    "documentations",
    "poPs",
    "resonances",
    "reactions",
    "sums",
    "fissionComponents",
    "productions",
    "applicationData"
})
@XmlRootElement(name = "reactionSuite")
public class ReactionSuite {

    @XmlElement(required = true)
    protected Styles styles;
    @XmlElement(required = true)
    protected Documentations documentations;
    @XmlElement(name = "PoPs", required = true)
    protected PoPs poPs;
    protected Resonances resonances;
    @XmlElement(required = true)
    protected Reactions reactions;
    protected Sums sums;
    protected FissionComponents fissionComponents;
    protected Productions productions;
    protected Object applicationData;
    @XmlAttribute(name = "projectile", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String projectile;
    @XmlAttribute(name = "target", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String target;
    @XmlAttribute(name = "evaluation", required = true)
    protected String evaluation;
    @XmlAttribute(name = "projectileFrame", required = true)
    protected Frame projectileFrame;
    @XmlAttribute(name = "version", required = true)
    protected String version;

    /**
     * Gets the value of the styles property.
     * 
     * @return
     *     possible object is
     *     {@link Styles }
     *     
     */
    public Styles getStyles() {
        return styles;
    }

    /**
     * Sets the value of the styles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Styles }
     *     
     */
    public void setStyles(Styles value) {
        this.styles = value;
    }

    /**
     * Gets the value of the documentations property.
     * 
     * @return
     *     possible object is
     *     {@link Documentations }
     *     
     */
    public Documentations getDocumentations() {
        return documentations;
    }

    /**
     * Sets the value of the documentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documentations }
     *     
     */
    public void setDocumentations(Documentations value) {
        this.documentations = value;
    }

    /**
     * Gets the value of the poPs property.
     * 
     * @return
     *     possible object is
     *     {@link PoPs }
     *     
     */
    public PoPs getPoPs() {
        return poPs;
    }

    /**
     * Sets the value of the poPs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoPs }
     *     
     */
    public void setPoPs(PoPs value) {
        this.poPs = value;
    }

    /**
     * Gets the value of the resonances property.
     * 
     * @return
     *     possible object is
     *     {@link Resonances }
     *     
     */
    public Resonances getResonances() {
        return resonances;
    }

    /**
     * Sets the value of the resonances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resonances }
     *     
     */
    public void setResonances(Resonances value) {
        this.resonances = value;
    }

    /**
     * Gets the value of the reactions property.
     * 
     * @return
     *     possible object is
     *     {@link Reactions }
     *     
     */
    public Reactions getReactions() {
        return reactions;
    }

    /**
     * Sets the value of the reactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reactions }
     *     
     */
    public void setReactions(Reactions value) {
        this.reactions = value;
    }

    /**
     * Gets the value of the sums property.
     * 
     * @return
     *     possible object is
     *     {@link Sums }
     *     
     */
    public Sums getSums() {
        return sums;
    }

    /**
     * Sets the value of the sums property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sums }
     *     
     */
    public void setSums(Sums value) {
        this.sums = value;
    }

    /**
     * Gets the value of the fissionComponents property.
     * 
     * @return
     *     possible object is
     *     {@link FissionComponents }
     *     
     */
    public FissionComponents getFissionComponents() {
        return fissionComponents;
    }

    /**
     * Sets the value of the fissionComponents property.
     * 
     * @param value
     *     allowed object is
     *     {@link FissionComponents }
     *     
     */
    public void setFissionComponents(FissionComponents value) {
        this.fissionComponents = value;
    }

    /**
     * Gets the value of the productions property.
     * 
     * @return
     *     possible object is
     *     {@link Productions }
     *     
     */
    public Productions getProductions() {
        return productions;
    }

    /**
     * Sets the value of the productions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Productions }
     *     
     */
    public void setProductions(Productions value) {
        this.productions = value;
    }

    /**
     * Gets the value of the applicationData property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getApplicationData() {
        return applicationData;
    }

    /**
     * Sets the value of the applicationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setApplicationData(Object value) {
        this.applicationData = value;
    }

    /**
     * Gets the value of the projectile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectile() {
        return projectile;
    }

    /**
     * Sets the value of the projectile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectile(String value) {
        this.projectile = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the evaluation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * Sets the value of the evaluation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvaluation(String value) {
        this.evaluation = value;
    }

    /**
     * Gets the value of the projectileFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Frame }
     *     
     */
    public Frame getProjectileFrame() {
        return projectileFrame;
    }

    /**
     * Sets the value of the projectileFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Frame }
     *     
     */
    public void setProjectileFrame(Frame value) {
        this.projectileFrame = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
