//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Reich_Moore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Reich_Moore">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scatteringRadius" type="{}scatteringRadius"/>
 *         &lt;element name="resonanceParameters" type="{}resonanceParameters"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LvaluesNeededForConvergence" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="calculateChannelRadius" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="computeAngularDistribution" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Reich_Moore", propOrder = {
    "scatteringRadius",
    "resonanceParameters"
})
public class ReichMoore {

    @XmlElement(required = true)
    protected ScatteringRadius scatteringRadius;
    @XmlElement(required = true)
    protected ResonanceParameters resonanceParameters;
    @XmlAttribute(name = "LvaluesNeededForConvergence", required = true)
    protected BigInteger lvaluesNeededForConvergence;
    @XmlAttribute(name = "calculateChannelRadius")
    protected Boolean calculateChannelRadius;
    @XmlAttribute(name = "computeAngularDistribution")
    protected Boolean computeAngularDistribution;

    /**
     * Gets the value of the scatteringRadius property.
     * 
     * @return
     *     possible object is
     *     {@link ScatteringRadius }
     *     
     */
    public ScatteringRadius getScatteringRadius() {
        return scatteringRadius;
    }

    /**
     * Sets the value of the scatteringRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScatteringRadius }
     *     
     */
    public void setScatteringRadius(ScatteringRadius value) {
        this.scatteringRadius = value;
    }

    /**
     * Gets the value of the resonanceParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ResonanceParameters }
     *     
     */
    public ResonanceParameters getResonanceParameters() {
        return resonanceParameters;
    }

    /**
     * Sets the value of the resonanceParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResonanceParameters }
     *     
     */
    public void setResonanceParameters(ResonanceParameters value) {
        this.resonanceParameters = value;
    }

    /**
     * Gets the value of the lvaluesNeededForConvergence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLvaluesNeededForConvergence() {
        return lvaluesNeededForConvergence;
    }

    /**
     * Sets the value of the lvaluesNeededForConvergence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLvaluesNeededForConvergence(BigInteger value) {
        this.lvaluesNeededForConvergence = value;
    }

    /**
     * Gets the value of the calculateChannelRadius property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCalculateChannelRadius() {
        return calculateChannelRadius;
    }

    /**
     * Sets the value of the calculateChannelRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCalculateChannelRadius(Boolean value) {
        this.calculateChannelRadius = value;
    }

    /**
     * Gets the value of the computeAngularDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isComputeAngularDistribution() {
        return computeAngularDistribution;
    }

    /**
     * Sets the value of the computeAngularDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setComputeAngularDistribution(Boolean value) {
        this.computeAngularDistribution = value;
    }

}
