//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="documentations" type="{}documentations" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="scatteringRadius" type="{}scatteringRadius"/>
 *           &lt;sequence>
 *             &lt;element name="resolved" type="{}resolved" minOccurs="0"/>
 *             &lt;element name="unresolved" type="{}unresolved" minOccurs="0"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentations",
    "scatteringRadius",
    "resolved",
    "unresolved"
})
@XmlRootElement(name = "resonances")
public class Resonances {

    protected Documentations documentations;
    protected ScatteringRadius scatteringRadius;
    protected Resolved resolved;
    protected Unresolved unresolved;

    /**
     * Gets the value of the documentations property.
     * 
     * @return
     *     possible object is
     *     {@link Documentations }
     *     
     */
    public Documentations getDocumentations() {
        return documentations;
    }

    /**
     * Sets the value of the documentations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Documentations }
     *     
     */
    public void setDocumentations(Documentations value) {
        this.documentations = value;
    }

    /**
     * Gets the value of the scatteringRadius property.
     * 
     * @return
     *     possible object is
     *     {@link ScatteringRadius }
     *     
     */
    public ScatteringRadius getScatteringRadius() {
        return scatteringRadius;
    }

    /**
     * Sets the value of the scatteringRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScatteringRadius }
     *     
     */
    public void setScatteringRadius(ScatteringRadius value) {
        this.scatteringRadius = value;
    }

    /**
     * Gets the value of the resolved property.
     * 
     * @return
     *     possible object is
     *     {@link Resolved }
     *     
     */
    public Resolved getResolved() {
        return resolved;
    }

    /**
     * Sets the value of the resolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resolved }
     *     
     */
    public void setResolved(Resolved value) {
        this.resolved = value;
    }

    /**
     * Gets the value of the unresolved property.
     * 
     * @return
     *     possible object is
     *     {@link Unresolved }
     *     
     */
    public Unresolved getUnresolved() {
        return unresolved;
    }

    /**
     * Sets the value of the unresolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link Unresolved }
     *     
     */
    public void setUnresolved(Unresolved value) {
        this.unresolved = value;
    }

}
