//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for R_Matrix_Limited complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="R_Matrix_Limited">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resonanceReactions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="resonanceReaction" type="{}resonanceReaction" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="spinGroup" type="{}RML_spinGroup" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="approximation" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="boundaryCondition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="calculatePenetrability" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="calculateChannelRadius" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "R_Matrix_Limited", propOrder = {
    "resonanceReactions",
    "spinGroup"
})
public class RMatrixLimited {

    @XmlElement(required = true)
    protected RMatrixLimited.ResonanceReactions resonanceReactions;
    @XmlElement(required = true)
    protected List<RMLSpinGroup> spinGroup;
    @XmlAttribute(name = "approximation", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String approximation;
    @XmlAttribute(name = "boundaryCondition", required = true)
    protected String boundaryCondition;
    @XmlAttribute(name = "calculatePenetrability")
    protected Boolean calculatePenetrability;
    @XmlAttribute(name = "calculateChannelRadius")
    protected Boolean calculateChannelRadius;

    /**
     * Gets the value of the resonanceReactions property.
     * 
     * @return
     *     possible object is
     *     {@link RMatrixLimited.ResonanceReactions }
     *     
     */
    public RMatrixLimited.ResonanceReactions getResonanceReactions() {
        return resonanceReactions;
    }

    /**
     * Sets the value of the resonanceReactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMatrixLimited.ResonanceReactions }
     *     
     */
    public void setResonanceReactions(RMatrixLimited.ResonanceReactions value) {
        this.resonanceReactions = value;
    }

    /**
     * Gets the value of the spinGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spinGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpinGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RMLSpinGroup }
     * 
     * 
     */
    public List<RMLSpinGroup> getSpinGroup() {
        if (spinGroup == null) {
            spinGroup = new ArrayList<RMLSpinGroup>();
        }
        return this.spinGroup;
    }

    /**
     * Gets the value of the approximation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApproximation() {
        return approximation;
    }

    /**
     * Sets the value of the approximation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApproximation(String value) {
        this.approximation = value;
    }

    /**
     * Gets the value of the boundaryCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBoundaryCondition() {
        return boundaryCondition;
    }

    /**
     * Sets the value of the boundaryCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBoundaryCondition(String value) {
        this.boundaryCondition = value;
    }

    /**
     * Gets the value of the calculatePenetrability property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCalculatePenetrability() {
        return calculatePenetrability;
    }

    /**
     * Sets the value of the calculatePenetrability property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCalculatePenetrability(Boolean value) {
        this.calculatePenetrability = value;
    }

    /**
     * Gets the value of the calculateChannelRadius property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCalculateChannelRadius() {
        return calculateChannelRadius;
    }

    /**
     * Sets the value of the calculateChannelRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCalculateChannelRadius(Boolean value) {
        this.calculateChannelRadius = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="resonanceReaction" type="{}resonanceReaction" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resonanceReaction"
    })
    public static class ResonanceReactions {

        @XmlElement(required = true)
        protected List<ResonanceReaction> resonanceReaction;

        /**
         * Gets the value of the resonanceReaction property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resonanceReaction property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResonanceReaction().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResonanceReaction }
         * 
         * 
         */
        public List<ResonanceReaction> getResonanceReaction() {
            if (resonanceReaction == null) {
                resonanceReaction = new ArrayList<ResonanceReaction>();
            }
            return this.resonanceReaction;
        }

    }

}
