//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RML_spinGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RML_spinGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="channels" type="{}RML_channels"/>
 *         &lt;element name="resonanceParameters" type="{}resonanceParameters" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="spin" use="required" type="{}fractionAttribute" />
 *       &lt;attribute name="parity" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RML_spinGroup", propOrder = {
    "channels",
    "resonanceParameters"
})
public class RMLSpinGroup {

    @XmlElement(required = true)
    protected RMLChannels channels;
    protected ResonanceParameters resonanceParameters;
    @XmlAttribute(name = "index", required = true)
    protected BigInteger index;
    @XmlAttribute(name = "spin", required = true)
    protected String spin;
    @XmlAttribute(name = "parity", required = true)
    protected BigInteger parity;

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link RMLChannels }
     *     
     */
    public RMLChannels getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link RMLChannels }
     *     
     */
    public void setChannels(RMLChannels value) {
        this.channels = value;
    }

    /**
     * Gets the value of the resonanceParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ResonanceParameters }
     *     
     */
    public ResonanceParameters getResonanceParameters() {
        return resonanceParameters;
    }

    /**
     * Sets the value of the resonanceParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResonanceParameters }
     *     
     */
    public void setResonanceParameters(ResonanceParameters value) {
        this.resonanceParameters = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the spin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpin() {
        return spin;
    }

    /**
     * Sets the value of the spin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpin(String value) {
        this.spin = value;
    }

    /**
     * Gets the value of the parity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParity() {
        return parity;
    }

    /**
     * Sets the value of the parity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParity(BigInteger value) {
        this.parity = value;
    }

}
