//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SingleLevel_BreitWigner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleLevel_BreitWigner">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scatteringRadius" type="{}scatteringRadius"/>
 *         &lt;element name="resonanceParameters" type="{}resonanceParameters"/>
 *       &lt;/sequence>
 *       &lt;attribute name="calculateChannelRadius" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleLevel_BreitWigner", propOrder = {
    "scatteringRadius",
    "resonanceParameters"
})
public class SingleLevelBreitWigner {

    @XmlElement(required = true)
    protected ScatteringRadius scatteringRadius;
    @XmlElement(required = true)
    protected ResonanceParameters resonanceParameters;
    @XmlAttribute(name = "calculateChannelRadius", required = true)
    protected boolean calculateChannelRadius;

    /**
     * Gets the value of the scatteringRadius property.
     * 
     * @return
     *     possible object is
     *     {@link ScatteringRadius }
     *     
     */
    public ScatteringRadius getScatteringRadius() {
        return scatteringRadius;
    }

    /**
     * Sets the value of the scatteringRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScatteringRadius }
     *     
     */
    public void setScatteringRadius(ScatteringRadius value) {
        this.scatteringRadius = value;
    }

    /**
     * Gets the value of the resonanceParameters property.
     * 
     * @return
     *     possible object is
     *     {@link ResonanceParameters }
     *     
     */
    public ResonanceParameters getResonanceParameters() {
        return resonanceParameters;
    }

    /**
     * Sets the value of the resonanceParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResonanceParameters }
     *     
     */
    public void setResonanceParameters(ResonanceParameters value) {
        this.resonanceParameters = value;
    }

    /**
     * Gets the value of the calculateChannelRadius property.
     * 
     */
    public boolean isCalculateChannelRadius() {
        return calculateChannelRadius;
    }

    /**
     * Sets the value of the calculateChannelRadius property.
     * 
     */
    public void setCalculateChannelRadius(boolean value) {
        this.calculateChannelRadius = value;
    }

}
