//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tabulatedWidths complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tabulatedWidths">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scatteringRadius" type="{}scatteringRadius"/>
 *         &lt;element name="L_section" type="{}URR_L_section" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="interpolation" use="required" type="{}interpolation" />
 *       &lt;attribute name="ENDFconversionFlag" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tabulatedWidths", propOrder = {
    "scatteringRadius",
    "lSection"
})
public class TabulatedWidths {

    @XmlElement(required = true)
    protected ScatteringRadius scatteringRadius;
    @XmlElement(name = "L_section", required = true)
    protected List<URRLSection> lSection;
    @XmlAttribute(name = "interpolation", required = true)
    protected Interpolation interpolation;
    @XmlAttribute(name = "ENDFconversionFlag", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String endFconversionFlag;

    /**
     * Gets the value of the scatteringRadius property.
     * 
     * @return
     *     possible object is
     *     {@link ScatteringRadius }
     *     
     */
    public ScatteringRadius getScatteringRadius() {
        return scatteringRadius;
    }

    /**
     * Sets the value of the scatteringRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScatteringRadius }
     *     
     */
    public void setScatteringRadius(ScatteringRadius value) {
        this.scatteringRadius = value;
    }

    /**
     * Gets the value of the lSection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lSection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link URRLSection }
     * 
     * 
     */
    public List<URRLSection> getLSection() {
        if (lSection == null) {
            lSection = new ArrayList<URRLSection>();
        }
        return this.lSection;
    }

    /**
     * Gets the value of the interpolation property.
     * 
     * @return
     *     possible object is
     *     {@link Interpolation }
     *     
     */
    public Interpolation getInterpolation() {
        return interpolation;
    }

    /**
     * Sets the value of the interpolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Interpolation }
     *     
     */
    public void setInterpolation(Interpolation value) {
        this.interpolation = value;
    }

    /**
     * Gets the value of the endFconversionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENDFconversionFlag() {
        return endFconversionFlag;
    }

    /**
     * Sets the value of the endFconversionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENDFconversionFlag(String value) {
        this.endFconversionFlag = value;
    }

}
