//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for unresolved complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="unresolved">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="tabulatedWidths" type="{}tabulatedWidths"/>
 *       &lt;/choice>
 *       &lt;attribute name="domainMin" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domainMax" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="domainUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formalism" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="reconstructCrossSection" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "unresolved", propOrder = {
    "tabulatedWidths"
})
public class Unresolved {

    protected TabulatedWidths tabulatedWidths;
    @XmlAttribute(name = "domainMin", required = true)
    protected double domainMin;
    @XmlAttribute(name = "domainMax", required = true)
    protected double domainMax;
    @XmlAttribute(name = "domainUnit", required = true)
    protected String domainUnit;
    @XmlAttribute(name = "formalism", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String formalism;
    @XmlAttribute(name = "reconstructCrossSection")
    protected Boolean reconstructCrossSection;

    /**
     * Gets the value of the tabulatedWidths property.
     * 
     * @return
     *     possible object is
     *     {@link TabulatedWidths }
     *     
     */
    public TabulatedWidths getTabulatedWidths() {
        return tabulatedWidths;
    }

    /**
     * Sets the value of the tabulatedWidths property.
     * 
     * @param value
     *     allowed object is
     *     {@link TabulatedWidths }
     *     
     */
    public void setTabulatedWidths(TabulatedWidths value) {
        this.tabulatedWidths = value;
    }

    /**
     * Gets the value of the domainMin property.
     * 
     */
    public double getDomainMin() {
        return domainMin;
    }

    /**
     * Sets the value of the domainMin property.
     * 
     */
    public void setDomainMin(double value) {
        this.domainMin = value;
    }

    /**
     * Gets the value of the domainMax property.
     * 
     */
    public double getDomainMax() {
        return domainMax;
    }

    /**
     * Sets the value of the domainMax property.
     * 
     */
    public void setDomainMax(double value) {
        this.domainMax = value;
    }

    /**
     * Gets the value of the domainUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomainUnit() {
        return domainUnit;
    }

    /**
     * Sets the value of the domainUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomainUnit(String value) {
        this.domainUnit = value;
    }

    /**
     * Gets the value of the formalism property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormalism() {
        return formalism;
    }

    /**
     * Sets the value of the formalism property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormalism(String value) {
        this.formalism = value;
    }

    /**
     * Gets the value of the reconstructCrossSection property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReconstructCrossSection() {
        return reconstructCrossSection;
    }

    /**
     * Sets the value of the reconstructCrossSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReconstructCrossSection(Boolean value) {
        this.reconstructCrossSection = value;
    }

}
