//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for URR_J_section complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="URR_J_section">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="constantWidths" type="{}URR_constantWidths" minOccurs="0"/>
 *         &lt;element name="energyDependentWidths" type="{}energyDependentWidths" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="J" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="neutronDOF" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="fissionDOF" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="competitiveDOF" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "URR_J_section", propOrder = {
    "constantWidths",
    "energyDependentWidths"
})
public class URRJSection {

    protected URRConstantWidths constantWidths;
    protected EnergyDependentWidths energyDependentWidths;
    @XmlAttribute(name = "J", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String j;
    @XmlAttribute(name = "neutronDOF", required = true)
    protected BigInteger neutronDOF;
    @XmlAttribute(name = "fissionDOF")
    protected BigInteger fissionDOF;
    @XmlAttribute(name = "competitiveDOF")
    protected BigDecimal competitiveDOF;

    /**
     * Gets the value of the constantWidths property.
     * 
     * @return
     *     possible object is
     *     {@link URRConstantWidths }
     *     
     */
    public URRConstantWidths getConstantWidths() {
        return constantWidths;
    }

    /**
     * Sets the value of the constantWidths property.
     * 
     * @param value
     *     allowed object is
     *     {@link URRConstantWidths }
     *     
     */
    public void setConstantWidths(URRConstantWidths value) {
        this.constantWidths = value;
    }

    /**
     * Gets the value of the energyDependentWidths property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyDependentWidths }
     *     
     */
    public EnergyDependentWidths getEnergyDependentWidths() {
        return energyDependentWidths;
    }

    /**
     * Sets the value of the energyDependentWidths property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyDependentWidths }
     *     
     */
    public void setEnergyDependentWidths(EnergyDependentWidths value) {
        this.energyDependentWidths = value;
    }

    /**
     * Gets the value of the j property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJ() {
        return j;
    }

    /**
     * Sets the value of the j property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJ(String value) {
        this.j = value;
    }

    /**
     * Gets the value of the neutronDOF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNeutronDOF() {
        return neutronDOF;
    }

    /**
     * Sets the value of the neutronDOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNeutronDOF(BigInteger value) {
        this.neutronDOF = value;
    }

    /**
     * Gets the value of the fissionDOF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFissionDOF() {
        return fissionDOF;
    }

    /**
     * Sets the value of the fissionDOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFissionDOF(BigInteger value) {
        this.fissionDOF = value;
    }

    /**
     * Gets the value of the competitiveDOF property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCompetitiveDOF() {
        return competitiveDOF;
    }

    /**
     * Sets the value of the competitiveDOF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCompetitiveDOF(BigDecimal value) {
        this.competitiveDOF = value;
    }

}
