//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.27 at 11:31:49 AM PDT 
//


package gnd_jax.GND;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xData_uncertainty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xData_uncertainty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="XYs1d" type="{}xData_XYs1d_primary"/>
 *         &lt;element name="polynomial1d" type="{}xData_polynomial_1d_primary"/>
 *         &lt;element name="link" type="{}xlink"/>
 *       &lt;/choice>
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="pdf" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="relation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xData_uncertainty", propOrder = {
    "xYs1D",
    "polynomial1D",
    "link"
})
public class XDataUncertainty {

    @XmlElement(name = "XYs1d")
    protected XDataXYs1DPrimary xYs1D;
    @XmlElement(name = "polynomial1d")
    protected XDataPolynomial1DPrimary polynomial1D;
    protected Xlink link;
    @XmlAttribute(name = "index")
    protected BigInteger index;
    @XmlAttribute(name = "label")
    protected String label;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "pdf")
    protected String pdf;
    @XmlAttribute(name = "relation")
    protected String relation;

    /**
     * Gets the value of the xYs1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataXYs1DPrimary }
     *     
     */
    public XDataXYs1DPrimary getXYs1D() {
        return xYs1D;
    }

    /**
     * Sets the value of the xYs1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataXYs1DPrimary }
     *     
     */
    public void setXYs1D(XDataXYs1DPrimary value) {
        this.xYs1D = value;
    }

    /**
     * Gets the value of the polynomial1D property.
     * 
     * @return
     *     possible object is
     *     {@link XDataPolynomial1DPrimary }
     *     
     */
    public XDataPolynomial1DPrimary getPolynomial1D() {
        return polynomial1D;
    }

    /**
     * Sets the value of the polynomial1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link XDataPolynomial1DPrimary }
     *     
     */
    public void setPolynomial1D(XDataPolynomial1DPrimary value) {
        this.polynomial1D = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link Xlink }
     *     
     */
    public Xlink getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xlink }
     *     
     */
    public void setLink(Xlink value) {
        this.link = value;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the pdf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdf() {
        return pdf;
    }

    /**
     * Sets the value of the pdf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdf(String value) {
        this.pdf = value;
    }

    /**
     * Gets the value of the relation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelation() {
        return relation;
    }

    /**
     * Sets the value of the relation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelation(String value) {
        this.relation = value;
    }

}
